/*





                                                                    R E G K E Y

 ------------------------------------------------------------------------------


                                                                   Version 3.20


                                    The Registration Key System For Programmers


                                                                    Source Code




          (C) Copyright Brian Pirie, 1993 - 1998. All Rights Reserved.

*/


/*
        FILE : rkval.c

     VERSION : 3.20

     PURPOSE : Source code for the RegKeyValidate() function

  NOTICE - The conditions of use of this source code are specified in the
           RegKey documentation. Use of the RegKey source code is subject
           to a non-disclosure agreement. Please remember that you are not
           permitted to redistribute this source code.
*/



#define BUILDING_REGKEY
#include "regkey.h"
#include "rkintern.h"



/* RegKeyValidate()                                                          */
/*                                                                           */
/* Checks whether a given registration string and registration key           */
/* combination is valid for a particular application, using the application- */
/* specific validation code that was generated by RegKeyNewCodeSet(). The    */
/* RKVALID pointed to by peRegistered is set to either RK_REGISTERED or      */
/* RK_UNREGISTERED, indicating whether or not the registration key and       */
/* registration string are valid. If you have registered RegKey, your own    */
/* name and RegKey registration key should be passed to this function to     */
/* disable the RegKey "unregistered" message.                                */
/*                                                                           */
/* This function is called from within your application each time it         */
/* executes, in order to determine whether it should operate in registered   */
/* or unregistered mode. This function is used with user-entered             */
/* registration keys; compare with RegKeyFileValidate().                     */
/*                                                                           */
/* szRegString         INPUT: Registration string                            */
/* szRegKey            INPUT: 20-digit registration key                      */
/* szValidationCode    INPUT: App's validation code                          */
/* szYourName          INPUT: Your name (if registered)                      */
/* nYourKey            INPUT: Your key (if registered)                       */
/* peRegistered        OUTPUT: Is key valid                                  */

/* FIXME: tweak this so it can build under both DOS and Windows
RKFUNCDEF RKRETURN RKCALL RegKeyValidate(
*/
#ifdef WIN32
#ifdef NOT_C_TARGET
#ifdef VB_TARGET
RKFUNCDEF RKRETURN pascal far __export rkv(
   const char *szRegString,
   const char *szRegKey,
   const char *szValidationCode,
   const char *szYourName,
   unsigned long int nYourKey,
   RKVALID *peRegistered)
#else
#ifdef PASCAL_TARGET
RKFUNCDEF RKRETURN rkv(
   const char *szRegString,
   const char *szRegKey,
   const char *szValidationCode,
   const char *szYourName,
   unsigned long int nYourKey,
   RKVALID *peRegistered)
#else
RKFUNCDEF RKRETURN rkv(
   const char *szRegString,
   const char *szRegKey,
   const char *szValidationCode,
   const char *szYourName,
   unsigned long int nYourKey,
   RKVALID *peRegistered)
#endif
#endif
#endif
#endif 

#ifdef MSDOS
#ifdef NOT_C_TARGET
#ifdef VBDOS_TARGET
RKFUNCDEF RKRETURN RKCALL rkv(
        CONST char* szRegString,
        CONST char* szRegKey,
        CONST char* szValidationCode,
        CONST char* szYourName,
        unsigned long int nYourKey,
        RKVALID* peRegistered)
#else
RKFUNCDEF RKRETURN RKCALL RegKeyValidate(
   CONST char *szRegString,
   CONST char *szRegKey,
   CONST char *szValidationCode,
   CONST char *szYourName,
   unsigned long int nYourKey,
   RKVALID *peRegistered)
#endif
#endif
#endif
{
   BIGINT bStringHash;
   BIGINT bR;
   BIGINT bS;
   BIGINT bLeft;
   BIGINT bRight;
   BIGINT bTemp;
   BIGINT bValCode;
   //BOOL *pbModInited;
   MODINFO *pRegKeyModInfo = regKeyModInfoGet();

   /* Validate Parameters */
   if(!szRegString || !szRegKey || !szValidationCode || !peRegistered)
   {
      return(RK_FAILURE);
   }

   /* Initialize modulus information, if not already done */
   initMod();

   /* Convert validation code from string to BIGINT representation */
   stringToB(&bValCode, szValidationCode);

   /* Convert registration key from string to BIGINT representation */
   stringToB(&bTemp, szRegKey);


   /* Registration key is formed of two pieces, bR and bS. */

   /* Get bR from upper half of registration key */
   bAssignWord(&bR, 0);
   bR.iWord[0] = bTemp.iWord[3];
   bR.iWord[1] = bTemp.iWord[4];
   bR.iWord[2] = bTemp.iWord[5];

   /* Get bS from lower half of registration key */
   bAssignWord(&bS, 0);
   bS.iWord[0] = bTemp.iWord[0];
   bS.iWord[1] = bTemp.iWord[1];
   bS.iWord[2] = bTemp.iWord[2];


   /* Registration key is valid iff:                                         */
   /*                                                                        */
   /* bRegKeyBase^bHash(szRegString) ==                                      */
   /*                           (bValCode ^ bR) * (bR ^ bS) (mod bRegKeyMod) */

   /* Calculate hash code of registration string */
   bHash(&bStringHash, szRegString, pRegKeyModInfo);

   /* Calculate bLeft = bRegKeyBase ^ bStringHash (mod bRegKeyMod) */
   bExpModN(&bLeft, bRegKeyBaseGet(), &bStringHash, pRegKeyModInfo);

   /* Calculate bRight = (bValCode ^ bR) * (bR ^ bS) (mod bRegKeyMod) */
   bExpModN(&bRight, &bValCode, &bR, pRegKeyModInfo);
   bExpModN(&bTemp, &bR, &bS, pRegKeyModInfo);
   bMult(&bRight, &bTemp);
   bMod(&bRight, pRegKeyModInfo);

   /* Registration key is valid iff bLeft == bRight */
   *peRegistered = (bEqual(&bLeft, &bRight) ? RK_REGISTERED : RK_UNREGISTERED);

   /* Return with success */
   return(RK_SUCCESS);
}
/*#ifdef NOT_C_TARGET
#ifdef VB_TARGET*/
//RKFUNCDEF RKRETURN rkv(
//   const char *szRegString,
//   const char *szRegKey,
//   const char *szValidationCode,
//   const char *szYourName,
//   unsigned long int nYourKey,
//   RKVALID *peRegistered)
/*#else
#ifdef PASCAL_TARGET
RKFUNCDEF RKRETURN rkv(
   const char *szRegString,
   const char *szRegKey,
   const char *szValidationCode,
   const char *szYourName,
   unsigned long int nYourKey,
   RKVALID *peRegistered)
#else
RKFUNCDEF RKRETURN rkv(
   const char *szRegString,
   const char *szRegKey,
   const char *szValidationCode,
   const char *szYourName,
   unsigned long int nYourKey,
   RKVALID *peRegistered)
#endif*/
//{
//	RKRETURN ret = RegKeyValidate(szRegString,szRegKey,szValidationCode,szYourName,nYourKey,peRegistered);
//	return ret;
//}
/*#endif*/
