//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by KeyGen.rc
//
#define ID_BUTTON_GENERATE              2
#define ID_BUTTON_INFO                  3
#define ID_BUTTON_ADD                   4
#define ID_BUTTON_DELETE                5
#define IDD_KEYGEN_DIALOG               102
#define IDD_DIALOG_GENERATE             105
#define IDD_DIALOG_NEW_APP              106
#define IDD_DIALOG_PASSWORD             108
#define IDD_DIALOG_APPINFO              109
#define IDD_DIALOG_KEYINFO              110
#define IDR_MAINFRAME                   128
#define IDC_EDIT_NAME                   1000
#define IDC_EDIT_GENERATION             1001
#define ID_LIST_APPS                    1019
#define IDC_EDIT_STRING                 1020
#define IDC_EDIT_PASSWORD               1021
#define IDC_STATIC_NAME                 1022
#define IDC_EDIT_FILENAME               1024
#define IDC_STATIC_FILENAME             1025
#define IDC_STATIC_PASSWORD             1026
#define IDC_RADIO_USER                  1028
#define IDC_RADIO_FILE                  1029
#define IDC_CHECK_PASSWORD              1033
#define IDC_EDIT_SEED                   1034
#define IDC_VALIDATION_CODE             1035
#define IDC_BUTTON_COPY                 1036
#define IDC_INFO_ICON                   1037
#define IDC_REGKEY                      1038

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
